# Generated by tools/localization/catalog.py; edit catalog.json.
extends RefCounted
const LANGUAGES := {"de": "Deutsch", "en": "English"}
const CATALOGS := [
	preload("res://localization/de.po"),
	preload("res://localization/en.po"),
]
