#!/usr/bin/env python3
"""Generate native Godot gettext resources from the shared translation catalog.

Run with --check in validation; without arguments to regenerate PO resources.
No third-party dependencies. Reject duplicate keys, missing translations and
changed placeholders before a translation can reach the game.
"""
import argparse
import json
import pathlib
import re
from collections import Counter

ROOT = pathlib.Path(__file__).resolve().parents[2]


def placeholders(text):
    named = Counter(re.findall(r"\{[A-Za-z_][A-Za-z0-9_]*\}", text))
    positional = re.findall(r"%(?!%)[-+0-9.]*[sdif]", text.replace("%%", ""))
    return named, positional


def build():
    data = json.loads((ROOT / "localization/catalog.json").read_text(encoding="utf-8"))
    assert data["schema"] == 1, "Unknown catalog schema"
    seen = set()
    for row in data["messages"]:
        assert row["key"] and row["key"] not in seen, f"Duplicate key: {row['key']}"
        seen.add(row["key"])
        if "plural_key" in row:
            assert row["plural_key"] not in seen, f"Duplicate plural key: {row['plural_key']}"
            seen.add(row["plural_key"])
        for locale in data["locales"]:
            assert row.get(locale), f"Missing {locale}: {row['key']}"
            assert placeholders(row[locale]) == placeholders(row["de"]), f"Placeholders differ: {row['key']} ({locale})"
            if "plural_key" in row:
                assert row.get(locale + "_plural"), f"Missing plural: {row['key']}"
                assert placeholders(row[locale + "_plural"]) == placeholders(row["de"]), f"Plural placeholders differ: {row['key']}"
    resources = {}
    quote = lambda text: json.dumps(text, ensure_ascii=False)
    names = {locale: metadata['name'] for locale, metadata in data['locales'].items()}
    registry = ['# Generated by tools/localization/catalog.py; edit catalog.json.',
                'extends RefCounted', 'const LANGUAGES := ' + json.dumps(names, ensure_ascii=False),
                'const CATALOGS := [']
    registry.extend(f'\tpreload("res://localization/{locale}.po"),' for locale in names)
    registry.append(']')
    resources[ROOT / 'localization/catalogs.gd'] = '\n'.join(registry) + '\n'
    for locale, metadata in data["locales"].items():
        lines = ['# Generated by tools/localization/catalog.py; edit catalog.json.', 'msgid ""', 'msgstr ""',
                 quote('Content-Type: text/plain; charset=UTF-8\n'), quote(f'Language: {locale}\n'),
                 quote(f'Plural-Forms: {metadata["plural_forms"]}\n'), '']
        for row in data["messages"]:
            lines.append('msgid ' + quote(row["key"]))
            if "plural_key" in row:
                lines.extend(['msgid_plural ' + quote(row["plural_key"]),
                              'msgstr[0] ' + quote(row[locale]), 'msgstr[1] ' + quote(row[locale + "_plural"])])
            else:
                lines.append('msgstr ' + quote(row[locale]))
            lines.append('')
        resources[ROOT / f'localization/{locale}.po'] = '\n'.join(lines)
    return resources, len(data["messages"])


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    resources, count = build()
    for path, content in resources.items():
        if args.check:
            assert path.exists() and path.read_text(encoding="utf-8") == content, f'Stale resource: {path.name}'
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    print(f'LOCALIZATION_CATALOG_PASSED: {count} messages, {len(resources) - 1} languages')
