extends RefCounted
## Read-only built-in designs. All geometry/stats/persistence use existing owners.
const Blueprint = preload("res://civilization/buildings/building_blueprint.gd")
const Assembly = preload("res://assembly/core/modular_assembly.gd")
const DIRECTORY: String = "res://civilization/buildings/templates/"


static func list_templates() -> Array[Dictionary]:
	var result: Array[Dictionary] = []
	var manifest: Variant = JSON.parse_string(FileAccess.get_file_as_string(DIRECTORY + "catalog.json"))
	if not manifest is Dictionary or manifest.get("schema") != 1:
		return result
	for entry in manifest.get("templates", []):
		if entry is Dictionary and not load_template(str(entry.get("id", ""))).is_empty():
			result.append(entry.duplicate(true))
	return result


static func load_template(template_id: String) -> Dictionary:
	var manifest: Variant = JSON.parse_string(FileAccess.get_file_as_string(DIRECTORY + "catalog.json"))
	if not manifest is Dictionary or manifest.get("schema") != 1:
		return {}
	for entry in manifest.get("templates", []):
		if not entry is Dictionary or str(entry.get("id", "")) != template_id:
			continue
		var relative: String = str(entry.get("path", ""))
		if not relative.begins_with("designs/") or relative.contains("..") or not relative.ends_with(".json"):
			return {}
		var text: String = FileAccess.get_file_as_string(DIRECTORY + relative)
		if not Blueprint.Contract.inspect_text(text, "building").ok:
			return {}
		var raw: Dictionary = JSON.parse_string(text)
		if raw.get("assembly_type") != "building" or raw.get("design_id") != entry.get("design_id") or raw.get("revision") != entry.get("revision"):
			return {}
		var origin: Dictionary = raw.get("metadata", {}).get("template", {})
		if origin.get("id") != template_id or origin.get("revision") != entry.get("revision"):
			return {}
		# Validate BEFORE compatibility normalization can replace missing parts.
		if not Blueprint.validate(raw).is_empty():
			return {}
		var loaded: Dictionary = Assembly.deserialize(raw)
		Blueprint.normalize(loaded)
		return loaded
	return {}


static func create_copy(template_id: String) -> Dictionary:
	var original: Dictionary = load_template(template_id)
	if original.is_empty():
		return {}
	var copy: Dictionary = original.duplicate(true)
	copy["design_id"] = Blueprint.Ids.create("design")
	copy["revision"] = 0
	# Default editor save uses names as filenames; fresh names avoid collisions.
	copy["name"] = str(original.name) + " · " + str(copy.design_id).right(8)
	copy.metadata.erase("template")
	copy.metadata["source_template"] = {
		"template_id": template_id,
		"design_id": original.design_id,
		"revision": original.revision,
		"source": "voxelverse-built-in",
	}
	for placement in copy.parts:
		placement["uid"] = Blueprint.Ids.create("part")
	return copy


## Explicit persistence of a new copy, never a browse/selection side effect.
## Uses DesignStore, including its campaign and future-version protections.
static func save_copy(copy: Dictionary) -> Dictionary:
	if not Blueprint.Contract.inspect(copy, "building").ok or not Blueprint.validate(copy).is_empty():
		return {"error": ERR_INVALID_DATA, "path": ""}
	var id: String = str(copy.get("design_id", ""))
	var template_id: String = str(copy.get("metadata", {}).get("source_template", {}).get("template_id", ""))
	var source: Dictionary = load_template(template_id)
	if source.is_empty() or id == str(source.design_id) or int(copy.get("revision", -1)) != 0:
		return {"error": ERR_INVALID_DATA, "path": ""}
	# IDs generated by create_copy are opaque, 128-bit lowercase hex.
	if not id.begins_with("design_") or id.length() != 39 or not id.substr(7).is_valid_hex_number(false):
		return {"error": ERR_INVALID_DATA, "path": ""}
	var path: String = Blueprint.DESIGN_DIR + "/" + id + ".json"
	if FileAccess.file_exists(path) or not Blueprint.Store.read_text(path).is_empty():
		return {"error": ERR_ALREADY_EXISTS, "path": ""}
	var error: Error = DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(Blueprint.DESIGN_DIR))
	if error == OK:
		error = Blueprint.save_to_file(copy, path, true)
	return {"error": error, "path": path if error == OK else ""}
